### ISSUE TITLE
Tasks are not idempotent on EL-based distros when initially absent

### ISSUE THREAD

**Issue by martialblog** [Icinga/ansible-collection-icinga#126]
When features are `state: absent` during an initial installation, some tasks remain in "changed". Only happends on EL-based distros

```yaml
- name: Icinga Server
  become: true
  vars:
    icinga2_features:
      - name: mainlog
        state: absent
    icinga2_config_directories:
      - zones.d/main
  roles:
    - icinga.icinga.repos
    - icinga.icinga.icinga2
```

Tasks:

```
TASK [icinga.icinga.icinga2 : feature mainlog FileLogger object] *
changed: [icinga.rocky.vagrant] => {"changed": true, "dest": "/var/tmp/icinga/features-available/mainlog.conf/10_filelogger-main-log", "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/var/tmp/icinga/features-available/mainlog.conf/", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 6, "state": "directory", "uid": 0}

TASK [icinga.icinga.icinga2 : collect empty config dirs] *
changed: [icinga.rocky.vagrant] => {"changed": true, "cmd": "find /var/tmp/icinga -type d -empty\n", "delta": "0:00:00.002647", "end": "2022-09-28 12:25:07.927197", "msg": "", "rc": 0, "start": "2022-09-28 12:25:07.924550", "stderr": "", "stderr_lines": [], "stdout": "/var/tmp/icinga/features-available/mainlog.conf", "stdout_lines": ["/var/tmp/icinga/features-available/mainlog.conf"]}

TASK [icinga.icinga.icinga2 : remove empty config dirs] *
changed: [icinga.rocky.vagrant] => (item=/var/tmp/icinga/features-available/mainlog.conf) => {"ansible_loop_var": "item", "changed": true, "item": "/var/tmp/icinga/features-available/mainlog.conf", "path": "/var/tmp/icinga/features-available/mainlog.conf", "state": "absent"}
```

How to recreate:

- New EL-based installation with a feature set to `state: absent`
- Re-run playbook and see changed tasks

Workaround:

- Enable the feature, run playbook, disable feature and the tasks stay in `ok`
