### ISSUE TITLE
Apt-Key is deprecated

### ISSUE THREAD

**Issue by mkayontour** [Icinga/ansible-collection-icinga#133]
On the debian install routine we get this following error. 

"Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8))"

Need to manually get the key and store it in "/etc/apt/trusted.gpg.d/"

**Comment by lbetz** [comment]
Key download:
curl -fsSL https://packages.icinga.com/icinga.key | tee /usr/share/keyrings/icinga.gpg

Add key reference and arch to sources.d/icinga.list:
deb [arch=amd64 signed-by=/usr/share/keyrings/icinga.gpg] https://packages.icinga...

**Comment by mkayontour** [comment]
Are there any disadvantages if we manage the key in **/etc/apt/trusted.gpg.d/** ? 

In this location I don't need to add the `signed-by` in the sources.d. 

```
- name: Apt - add repository key
   become: yes
   ansible.builtin.get_url:
     url: "{{ icinga_repo_apt_key }}"
     dest: /etc/apt/trusted.gpg.d/icinga.asc
     mode: '0644'
     force: true
```
