### ISSUE TITLE
icinga2: error when icinga2_config_directories is not defined

### ISSUE THREAD

**Issue by mkayontour** [Icinga/ansible-collection-icinga#141]
If you define icinga2_objects with a File which is missing the right directory. 

```
icinga2_config_directories:
  - zones.d/main
```

```
icinga2_objects:
  [...]
  - name: host1
     type: Host
     file: zones.d/main/hosts/hosts.conf
```

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: b'/home/vagrant/.ansible/tmp/ansible-tmp-1675090546.848353-6236-143781702702531/tmph71p_wn6' -> b'/etc/icinga2/zones.d/main/hosts/hosts.conf'
failed: [icingadb] (item={'path': '/var/tmp/icinga/zones.d/main/hosts/hosts.conf'
```

Should check if icinga2_objects are defined and then if icinga2_config_directories are too.
