### ISSUE TITLE
icinga2_objects ApiUser does not work with ansible-vault

### ISSUE THREAD

**Issue by tomdymond** [Icinga/ansible-collection-icinga#146]
When trying to use an encrypted secret for the Api User as defined below in `group_vars/all/public.yml`:

```
icinga2_objects:
  "master1.localdomain":
    - name: icinga-api
      type: ApiUser
      file: conf.d/apiuser.conf
      password: "{{ vault_icinga2_apiuser_password }}"
      permissions:
        - "objects/query/Host"
        - "objects/query/Service"
      order: 1
```

and defining it in `group_vars/all/vars` below:

```
---
vault_icinga2_apiuser_password: MyIcinga2ApiUserDummyPassword
```

The result puts non interpolated password variable:

```
cat /etc/icinga2/conf.d/apiuser.conf
object ApiUser "icinga-api" {
  password = {{  vault_icinga2_apiuser_password  }}
  permissions = [ "objects/query/Host", "objects/query/Service", ]
}
```

The play shows that it has successfully rendered the file with the vault password but subsequently replaced it with another version that is not interpolated

```
TASK [icinga2 : icinga2_object] ************************************************
changed: [master1.localdomain] => (item={'name': 'icinga-api', 'type': 'ApiUser', 'file': 'conf.d/apiuser.conf', 'password': 'MyIcinga2ApiUserDummyPassword', 'permissions': ['objects/query/Host', 'objects/query/Service'], 'order': 1})
changed: [master1.localdomain] => (item={'name': 'icinga-api', 'type': 'ApiUser', 'file': 'conf.d/apiuser.conf', 'password': '{{ vault_icinga2_apiuser_password }}', 'permissions': ['objects/query/Host', 'objects/query/Service'], 'order': 1})

```

**Comment by martialblog** [comment]
Hi, thanks for the hint. We'll have a look at it.

**Comment by mkayontour** [comment]
hello @tomdymond can you please check if the PR #142 would fix your Issue. It should resolve the issue and it will be available in the next release.

**Comment by tomdymond** [comment]
thank you @mkayontour for fixing this for me. Am i correct in thinking the following will allow me to test this ? 
in `requirements.yml`
```
collections:
  - name: https://github.com/Icinga/ansible-collection-icinga.git
    type: git
    version: aa6e5b8ebe16c3d06189115568dd4130b3a2cfe2
```
Because I get
```
ERROR! Collection artifact at '/home/vagrant/.ansible/tmp/ansible-local-139889yy6pedk7/tmpvvkhier2/ansible-collection-icingazch4dl8p.git' is not a valid tar file.
``

Apologies if this is documented elsewhere and I was unable to find it
