### ISSUE TITLE
The icinga2 role wrongly include parent vars file instead of its own

### ISSUE THREAD

**Issue by sebastienthirion** [Icinga/ansible-collection-icinga#148]
For example, let's say that I have a role with the following directory structure that I want to apply to a Debian 11 system:
```
.
├── defaults
├── tasks
│   ├── main.yml
└── vars
    └── Debian-11.yml
```
And that my `main.yml` file includes the `icinga2` role.

Because [the `first_found` lookup plugin is going up the chain before giving up on a file](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/first_found_lookup.html#id1), my `Debian-11.yml` var file file is found before the `Debian.yml` var file of the `icinga2` role in [Icinga's main.yml tasks file](https://github.com/Icinga/ansible-collection-icinga/blob/880ad7d9c5f116d2b9bf632a5d6136880b9bab36/roles/icinga2/tasks/main.yml):

```yaml
- name: Include OS specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml" # <-- My Debian-11.yml
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml" # <-- Icinga Debian.yml
        - default.yml
      paths:
        - 'vars'
```

Unless I missed something, this lookup is unnecessary because the var files that exist inside the role will only ever match `"{{ ansible_os_family }}.yml"` or `default.yml` (but `default.yml` is empty so this one does not really matter).

IHMO, this could be replaced by a way more simple `include_vars`:
```yaml
- name: Include OS specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
```

The `repos` role should have the same issue as well (though I have not tested that).

Again, maybe there is a really good reason for doing this that I am not aware of.

**Comment by martialblog** [comment]
Hey, so the idea behind this code is for us to use the `vars` dir to store variable files for the various Distros/Versions. I.e. the user is different on RHEL and Debian based systems `icinga2_user: nagios`. 

Since these vars could differ depending on the distro/major_version/etc we use the hierarchy you see. So if Debian 12 wants to use `icinga2_user: foobar` we can simply add a `Debian-12.yml` and we're done.

If you want to provide your own values, you would include the role on a playbook and then override the variables there. 

```
host_vars/
   my-icinga-master.yml 

cat playbooks/icinga-master.yaml
---
- hosts: my-icinga-master
  roles:
    - icinga.icinga.repos
    - icinga.icinga.icinga2
```

**Comment by sebastienthirion** [comment]
I can reproduce the issue with a barebone playbook only including both icinga roles and by creating an empty `Debian-11.yml` file in a `vars` folder:
```yaml
# playbook.yaml
---
- hosts: debian11
  become: true
  roles:
  - icinga.icinga.repos
  - icinga.icinga.icinga2
```
```
.
├── playbook.yaml
└── vars
    └── Debian-11.yml
```

Here is the relevant output of `ansible-playbook` showing the `include_vars` tasks importing the wrong file:
```
$ ansible-playbook -vvv playbook.yaml

...

TASK [icinga.icinga.icinga2 : Include OS specific vars] ************************
task path: /home/user/.ansible/collections/ansible_collections/icinga/icinga/roles/icinga2/tasks/main.yml:4
ok: [debian11] => {
    "ansible_facts": {},
    "ansible_included_var_files": [
        "/home/user/test/vars/Debian-11.yml"
    ],
    "changed": false
}

...

TASK [icinga.icinga.icinga2 : fragments dir] ***********************************
task path: /home/user/.ansible/collections/ansible_collections/icinga/icinga/roles/icinga2/tasks/install.yml:6
fatal: [debian11]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'icinga2_fragments_path' is undefined\n\nThe error appears to be in '/home/user/.ansible/collections/ansible_collections/icinga/icinga/roles/icinga2/tasks/install.yml': line 6, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: fragments dir\n  ^ here\n"
}
```
