### ISSUE TITLE
icinga.repos not supporting setting a proxy for RedHat systems

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/ansible-collection-icinga#167]
Hi all,
For RedHat systems: If you have to use a proxy for the icinga repository, it is currently not possible to set one, although the ansible module yum_repository allows to set a proxy: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html#parameter-proxy

Cheers,
Marcus

**Comment by martialblog** [comment]
Hi, thanks for the hint. We'll have a look, shoud be fairly simple to add this

**Comment by mkayontour** [comment]
I need to check how to implement the feature. If it's not easy maintainable i suggest to use module defaults. I guess you will use the proxy for other repo tasks too. 

```
- hosts: localhost
  module_defaults:
    ansible.builtin.yum_repository:
      proxy: my.proxy:port
      proxy_username: proxy
      proxy_password: proxypass
```
