### ISSUE TITLE
Make enablerepo changeable in monitoring-plugins role

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/ansible-collection-icinga#173]
Morning all,
enablerepo in the monitoring role is set statically to several repos: https://github.com/Icinga/ansible-collection-icinga/blob/main/roles/monitoring_plugins/tasks/install_on_RedHat.yml#L30
But I have to install the plugins from a specific repo. So be able to overwrite the given repos would be nice.
To fix this locally, I have set 'enablerepo' to a new icinga variable with it's default in the defaults file. 

```
- name: Dnf - install requested packages
  become: yes
  dnf:
    state: present
    name: "{{ needed_packages }}"
    update_cache: true
    enablerepo: "{{ icinga_monitoring_plugins_enablerepo }}"
  when:
    - ansible_distribution_major_version >= "8"
    - needed_packages is defined
    - needed_packages
```

`icinga_monitoring_plugins_enablerepo: "{{ 'powertools' if ansible_distribution_major_version == '8' and icinga_monitoring_plugins_crb else 'crb' if ansible_distribution_major_version == '9' and icinga_monitoring_plugins_crb }}"
`

Cheers,
Marcus
