### ISSUE TITLE
[icingaweb2] unable to use ldap resources

### ISSUE THREAD

**Issue by Yoda-BZH** [Icinga/ansible-collection-icinga#176]
Hello,

When using `icingaweb2_resources` to declare ldap resources, some values may be left out if they contains `=`, which they definitely have.

example:
```
icingaweb2_resources:
  ad:
    type: ldap
    hostname: ldap.example.com
    port: 389
    root_dn: "OU=users,OU=example,DC=example,DC=com"
    bind_dn: "CN=accountname,,OU=users,OU=example,DC=example,DC=com"
    bind_pw: this-is-a-password
    encryption: starttls
```

because of https://github.com/Icinga/ansible-collection-icinga/commit/4077df4d7aef3c351057596948c55845099923ee#diff-e077016061b8c4a46d3232abd4ce5d0cefd124d4cc439e506f1af2dc143530d6R8-R9, `rood_dn` and `bind_dn` will be ignore and absent of resources.ini :
```
{% elif value is string and "=" in value %}
{% else %}
```

I don't know why this condition is present, and what is the intended purpose. It may be removed, of perhaps the quotes should be enforced around the value, because of the `=` sign.
