### ISSUE TITLE
Add object HostGroup

### ISSUE THREAD

**Issue by mkayontour** [Icinga/ansible-collection-icinga#22]

**Comment by mkayontour** [comment]
Example: 

```
    - name: "host_group_linux"
      type: HostGroup
      file: "local.d/groups.conf"
      display_name: Linux Hosts
      assign:
        - host.vars.os == linux
```
