### ISSUE TITLE
Display proper fail messages if OS not supported

### ISSUE THREAD

**Issue by johanneskastl** [Icinga/ansible-collection-icinga#232]
Is it intentional that there is no `install_on_suse.yml` file in the icinga.icinga.icingadb_redis role?

https://github.com/Icinga/ansible-collection-icinga/blob/main/roles/icingadb_redis/tasks/main.yml#L15

```
- name: Include OS specific installation
  ansible.builtin.include_tasks: "install_on_{{ ansible_os_family | lower }}.yml"
```

If so, the role should fail and report, that the installation on SUSE/openSUSE is not (yet) supported.

**Comment by mkayontour** [comment]
This is not intentional, yes we should at least state that the current os is not supported. And don't let it fail completely. 
I haven't got the time and resources yet to implement it! If possible you can create a PR, we are grateful for any contribution :)

**Comment by martialblog** [comment]
The supported platforms are stated in the metadata:

```yaml
  platforms:
    - name: EL
      versions: ['7']
    - name: Debian
      versions: ['buster','bullseye']
    - name: Ubuntu
      versions: ['jammy']
```

Unfortunately Ansible doesn't show you that on execution.
