### ISSUE TITLE
icinga2 role: How to create an api user for e.g. director?

### ISSUE THREAD

**Issue by johanneskastl** [Icinga/ansible-collection-icinga#242]
Sorry if this documented and I did just not find it:

Is there a way to create an API user for the icinga2 API, that can then be used by e.g. directory?

The README documents the API feature, but does not mention creating a user...

**Comment by mkayontour** [comment]
As the API User is just a regular object which can be created, it is meant to be created within `icinga2_objects`.

Example for a local apiuser, but path can be anything you like as long as the path is predefined in `icinga2_config_directories`: 
```
icinga2_objects:
  inserthostname:
    - name: myapiuser
      type: ApiUser
      file: conf.d/apiusers.conf
      password: secrectpassword
      permissions:
        - '*'
```

**Comment by johanneskastl** [comment]
Thanks, that was quick. I'll give it a try.

**Comment by johanneskastl** [comment]
OK, this almost works. But is there a way to use an Ansible variable instead of `inserthostname`? Can I use the `nodeName` constant here?

**Comment by mkayontour** [comment]
The constant is not working in this area, Ansible does not support a variable in dict keys. Somehow there are workarounds like the following (works in debug module outputs), the task "collect config objects" will be skipped. 

```yaml
icinga2_objects: "{
  '{{ ansible_fqdn }}':
    - name: root
      type: ApiUser
      file: conf.d/apiusers.conf
      password: root
      permissions:
        - '*'
}"
```
