### ISSUE TITLE
Add object TimePeriod

### ISSUE THREAD

**Issue by mkayontour** [Icinga/ansible-collection-icinga#27]

**Comment by mkayontour** [comment]
Example: 

```
    - name: 24x7
      type: TimePeriod
      file: "local.d/timeperiods.conf"
      ranges:
        monday: "00:00-24:00"
        tuesday: "00:00-24:00"
        wednesday: "00:00-24:00"
        thursday: "00:00-24:00"
        friday: "00:00-24:00"
```
