### ISSUE TITLE
Add documentation how to configure icingadb tls connection to redis

### ISSUE THREAD

**Issue by mkayontour** [Icinga/ansible-collection-icinga#272]
This information is also missing in the official documentation. So nobody will find it without trying in a running webfronted first. 

When tls is configured in icingaweb2 then this information is written to the config file. 
```
[redis]
tls = "1"
ca = "/var/lib/icingaweb2/modules/icingadb/redis/50178bbbb4d1692340de05261a89143f-ca.pem"
cert = "/var/lib/icingaweb2/modules/icingadb/redis/c342c4b909c519ef7d92fa5b83b1d297-cert.pem"
key = "/var/lib/icingaweb2/modules/icingadb/redis/fe572d2948de339b41f575f3f840bc0b-key.pem"
```

So this needs to be explained and visible in out docs. 

```
icingaweb2_modules:
  icingadb:
    enabled: true
    source: package
    commandtransports:
      instance01:
        transport: api
        host: 127.0.0.1
        username: root
        password: root
    config:
      icingadb:
        resource: icingadb
      redis:
        tls: '1'
        ca: /path/to/ca.crt
        cert: /path/to/cert.crt
        key: /path/to/key.key
```
