### ISSUE TITLE
Icingaweb2 issue when rendering LDAP Filter or LDAP Base DN

### ISSUE THREAD

**Issue by lucagubler** [Icinga/ansible-collection-icinga#301]
Hi all

I'm currently trying to connect Icinga Web to the AD so that employees can log in with their login. Unfortunately, this doesn't quite work with the Ansible Collection. Single quotes are added to the LDAP filter and LDAP base DN, which isn't supposed to happen. When I validate the config in the GUI, I get a "bad search filter" error. If I then manually remove the single quotes, the config validates successfully.

You can see the config below. I also tried removing the single quotes with `-:"xyz"`. But then single quotes are simply added around the whole string...

e.g. `filter: -:"(objectClass=*)"` &rarr; `filter = '-:"(objectClass=*)"'`

here's my config:
```yml
icingaweb2_authentication:
  icingaweb_ldap:
    resource: icingaweb_ldap
    filter: (objectClass=*)
    backend: "msldap"
    base_dn: OU=employees, OU=users, OU=prod, DC=ad, DC=example, DC=com
```

## Invalid AD config with single quotes
![Invalid AD config with single quotes](https://github.com/user-attachments/assets/f3a764a9-a1a1-415b-a6d8-047187626f30)

## Valid AD config without single quotes
![Valid AD config without single quotes](https://github.com/user-attachments/assets/302ecb7c-6f07-462b-b59e-32e5b051e18c)
