### ISSUE TITLE
Import of x509 database MySQL schema fails

### ISSUE THREAD

**Issue by Donien** [Icinga/ansible-collection-icinga#303]
When trying to import the **MySQL** database schema for the x509 module as laid out by the [docs](https://github.com/Icinga/ansible-collection-icinga/blob/5f2e504189e2ab2e0e4ac684d31b5dc21ffa138e/doc/role-icingaweb2/module-x509.md), the import fails due to the wrong variable name being referenced ([`schema_path` instead of `schema_path_mysql`](https://github.com/Icinga/ansible-collection-icinga/blob/4d5779374ea4ec65e5eb2cfcbe9d691283dd307e/roles/icingaweb2/tasks/manage_mysql_imports.yml#L36)).

## Reproduce

Snippet:

```yaml
vars:
  ...
  icingaweb2_modules:
    x509:
      source: package
      enabled: true
      config:
        backend:
          resource: "x509_db"
      database:
        import_schema: true
        type: mysql
        user: "x509"
        password: "pwd"
```

---

Side note:  
The role also fails at a `ansible.builtin.fail` task (if missing a needed variable). But ironically it fails due to the wrong module argument being passed (`fail_msg` instead of `msg`).  
Thus the intended fail message is never seen.
