### ISSUE TITLE
ini-configuration-tests need adjustment

### ISSUE THREAD

**Issue by Donien** [Icinga/ansible-collection-icinga#314]
As can be seen in this [job](https://github.com/Icinga/ansible-collection-icinga/actions/runs/10177427436/job/28148897755) the [ini-configuration-tests](https://github.com/Icinga/ansible-collection-icinga/blob/1a57b87c266983d33cfbdc2adf4e9bffcee9ded6/.github/workflows/test_icingaweb2_ini_template.yml#L33-L37) need an adjustment due to `ansible-core==2.16.4` not being available for `python==3.9`.

**Comment by mkayontour** [comment]
As this is often a Problem, can you separate and create two "jobs" which have their own matrix. 

Best would be three jobs for each version of non EOL core and then we can add for the specific core version the "python versions" 

```
      matrix:
        distro: [ubuntu2204]
        ansible: ['2.15.x']
        python: ['3.9','3.10','3.11']

```

https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix
