### ISSUE TITLE
Add documentation for authentication in icingaweb2 role

### ISSUE THREAD

**Issue by losten-git** [Icinga/ansible-collection-icinga#318]
Found out by browsing the `default.yml` that the authentication.ini can be managed with the icingaweb2 role. But its never mentioned in the docs. Would like to see a section in the documentation.
``` 
icingaweb2_authentication:
  icingaweb2:
    backend: db
    resource: icingaweb2_db
```
