### ISSUE TITLE
Bug(?): icinga-director kickstart in fullstack playbook not working

### ISSUE THREAD

**Issue by tbauriedel** [Icinga/ansible-collection-icinga#319]
The kickstart of the icinga-director cannot be executed in a single fullstack deployment.  
The required state of Icinga 2 for the kickstart is created by the restart handler. The handler is executed at the end of all roles.
If you want to install and kickstart the icinga-director in order to have a complete setup, this will fail because the Icinga 2 handler was logically not yet running at this point.

There are workarounds:
* `run_kickstart: false` and kickstart manually
* Create a second play with `icinga.icinga.icingaweb2` only, that is started afterwards.

In my opinion a fullstack deployment (including icinga-director kickstart) should work. It could be a idea to flush the handlers after the icinga2 role.

The best-practice from Ansible's point of view with handlers unfortunately collides with the functionality of the icinga components.

**Comment by mkayontour** [comment]
You can also use [Flush Handlers](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html)

```
tasks:
   - shell: some tasks go here
   - meta: flush_handlers
```

**Comment by mkayontour** [comment]
Did you try to use flush_handlers in the playbook? Would this be a viable option to use?

**Comment by tbauriedel** [comment]
Sorry for the late response.

Sure, flushing could "solve" this.
But in a deployment in which the roles are not called by includes within tasks, but only by `roles: [...]` this will not work.  
I could be wrong here, but from my point of view it should be possible to execute a single playbook without additional tasks to include roles or flush handlers.

**Comment by thesefer** [comment]
```
- hosts: domain.net
  become: yes
  tasks:
    - ansible.builtin.include_role:
        name: int.ntp
        apply:
          tags: icinga
      tags: always
    - ansible.builtin.include_role:
        name: int.env
    - ansible.builtin.include_role:
        name: int.apt
    # - { role: int.certbot, tags: ['certbot'] }
    - ansible.builtin.include_role:
        name: geerlingguy.mysql
        apply:
          tags: mysql
      tags: always
    - ansible.builtin.include_role:
        name: icinga.icinga.repos
        apply:
          tags: icinga
      tags: always
    - ansible.builtin.include_role:
        name: icinga.icinga.icinga2
        apply:
          tags: icinga
      tags: always
    - ansible.builtin.include_role:
        name: icinga.icinga.icingadb
        apply:
          tags: icinga
      tags: always
    - ansible.builtin.include_role:
        name: icinga.icinga.icingadb_redis
        apply:
          tags: icinga
      tags: always
    - ansible.builtin.include_role:
        name: icinga.icinga.monitoring_plugins
        apply:
          tags: icinga
      tags: always
    - meta: flush_handlers
      tags: icinga
    - ansible.builtin.include_role:
        name: icinga.icinga.icingaweb2
        apply:
          tags: icinga,icingaweb2
      tags: always
```

Results in the following error
```
TASK [icinga.icinga.icingaweb2 : Module Director | Run kickstart if required _raw_params=icingacli director kickstart run] ***********************************************************************************************************************************************************************************************
fatal: [domain.net]: FAILED! => {"changed": true, "cmd": "icingacli director kickstart run", "delta": "0:00:00.141587", "end": "2024-10-14 10:59:23.531171", "msg": "non-zero return code", "rc": 1, "start": "2024-10-14 10:59:23.389584", "stderr": "ERROR: RuntimeException in /usr/share/icingaweb2/modules/director/library/Director/Core/RestApiClient.php:149 with message: Unable to authenticate, please check your API credentials", "stderr_lines": ["ERROR: RuntimeException in /usr/share/icingaweb2/modules/director/library/Director/Core/RestApiClient.php:149 with message: Unable to authenticate, please check your API credentials"], "stdout": "", "stdout_lines": []}
```

I see the api credentials in `/etc/icinga2/conf.d/api-users.conf`
