### ISSUE TITLE
Undefined `icinga_objects` crashes playbook

### ISSUE THREAD

**Issue by C0rn3j** [Icinga/ansible-collection-icinga#332]
Worked around/fixed by changing

```yaml
  when: vars['icinga2_objects'][icinga2_config_host] is not defined
```
to
```yaml
  when: vars['icinga2_objects'] is defined and vars['icinga2_objects'][icinga2_config_host] is not defined
```
```yaml
TASK [icinga.icinga.icinga2 : collect all config objects in play vars] *****************************************************************************************************************************************************************************************************************************************************
fatal: [agent]: FAILED! => 
    msg: |-
        The task includes an option with an undefined variable. The error was: 'icinga2_objects' is undefined. 'icinga2_objects' is undefined

        The error appears to be in '/root/.ansible/collections/ansible_collections/icinga/icinga/roles/icinga2/tasks/objects.yml': line 8, column 3, but may
        be elsewhere in the file depending on the exact syntax problem.

        The offending line appears to be:


        - name: collect all config objects in play vars
          ^ here
```

Playbook:
```yaml
- name: Install icinga agent 
  hosts: "agent"
  roles:
    - add_repo
    - icinga.icinga.icinga2
  vars:
    repository: icinga  # add_repo
    icinga2_confd: false
    icinga2_purge_features: yes
    icinga2_delegate_host: 'master.example.com'
    icinga2_features:
      - name: api
        ca_host: '123.123.123.123'
        ca_host_port: '5665'
        endpoints:
          - name: NodeName
        zones:
          - name: ZoneName
            endpoints:
              - NodeName
      - name: notification
        state: absent
```
