### ISSUE TITLE
Bug when dict key is an integer

### ISSUE THREAD

**Issue by lucagubler** [Icinga/ansible-collection-icinga#342]
Hi all

I think there's a bug when we process a dict where the key is an integer. I added a JSON object to a device in NetBox and want to load and append this JSON to a Host object. The key is an AS number, e.g. `1234`. Inside of the NetBox dict, this key is surrounded by quotes. However, the Icinga2Parser detects this as integer and doesn't add quotes around it, which will lead to an invalid config.

actual rendered example_host.conf
```
object Host "rt01zrh2.wlp.is" {
  ...
  vars.nb["config"] = {
    bgp_sessions = {
      asn = {
        1234 = "BGP 1"
        2345 = "BGP 2"
    }
  }
}
```

desired outcome with quotes around the AS number
```
object Host "rt01zrh2.wlp.is" {
  ...
  vars.nb["config"] = {
    bgp_sessions = {
      asn = {
        "1234" = "BGP 1"
        "2345" = "BGP 2"
    }
  }
}
```

**Comment by Donien** [comment]
Hi @lucagubler :)

This issue went under the radar.  
But it seems to be fixed by now regardless. I believe #346 solved it.

At least it works for me with this input:

> Using the current main branch (eb777cc33632a4567ce5934ce77798868e8b8f85)

```yaml
icinga2_objects:
  - name: foo
    type: Host
    file: "local.d/hosts.conf"
    check_command: dummy
    vars:
      nb:
        config:
          bgp_sessions:
            something: else
            1234: foobar
```

Resulting config file:

```
object Host "foo" {

  check_command = "dummy"
  vars.nb["config"] = {
    bgp_sessions = {
      asn = {
        something = "else"
        "1234" = "foobar"
      }
    }
  }
}
```


I am closing the issue. Feel free to let us know if it is still a problem :)
