### ISSUE TITLE
Additional default zones

### ISSUE THREAD

**Issue by thesefer** [Icinga/ansible-collection-icinga#358]
hi, I might be overlooking something here, but is it possible or intended to create additional default zones as required per https://icinga.com/docs/icinga-director/latest/doc/04-Getting-started/  and https://github.com/Icinga/icinga2/blob/master/etc/icinga2/zones.conf?

Meaning I would need to create the following to zone objects:
```
object Zone "global-templates" {
	global = true
}

object Zone "director-global" {
	global = true
}
```

I expected to be able to create those during the initial setup as they are required or them being created by default by the collection, without having to use https://github.com/T-Systems-MMS/ansible-collection-icinga-director/blob/master/roles/ansible_icinga/tasks/icinga_zone.yml.

Hope you can help me here or clear things up
best regards

**Comment by thesefer** [comment]
Despite seeing it in icinga2_features I didn't expect it in the "api" features feature.
-> https://github.com/Icinga/ansible-collection-icinga/blob/main/doc/role-icinga2/features/feature-api.md

```
icinga2_features:
  - name: api
    ca_host: none
    cert_name: "{{ inventory_hostname }}"
    endpoints:
      - name: NodeName
      - name: master2
    zones:
      - name: ZoneName
        endpoints:
          - NodeName
          - master2
      - name: global-templates
        global: true
      - name: director-global
        global: true
```
