### ISSUE TITLE
icinga2_object ApiListener not idempotent

### ISSUE THREAD

**Issue by thesefer** [Icinga/ansible-collection-icinga#359]
I am currently trying to setup an agent and noticed that the type `ApiListener` from `icinga2_object` does not seem to be idempotent. It always reverts back to a default to apply a new value. The var is configured in `host_vars\myhost.example.net.yml`

Try 1
```
icinga2_objects:
  - name: api
    type: ApiListener
    accept_config: true
    accept_commands: true
```

Try 2
```
icinga2_objects:
  myhost.example.net:
    - name: api
      type: ApiListener
      accept_config: true
      accept_commands: true
```

Output:
```
[...]

TASK [icinga.icinga.icinga2 : api feature cleanup arguments list args={{ args|default({}) | combine({idx.key: idx.value}) }}] *********************************************************************************************************************************************************************************
ok: [myhost.example.net] => (item={'key': 'name', 'value': 'api'})
skipping: [myhost.example.net] => (item={'key': 'ca_host', 'value': 'master.example.net'}) 
skipping: [myhost.example.net] => (item={'key': 'cert_name', 'value': 'myhost.example.net'}) 
skipping: [myhost.example.net] => (item={'key': 'endpoints', 'value': [{'name': 'NodeName'}, {'name': 'master.example.net'}, {'name': 'master2.example.net'}]}) 
skipping: [myhost.example.net] => (item={'key': 'zones', 'value': [{'name': 'NodeName', 'parent': 'main', 'endpoints': ['NodeName']}, {'name': 'main', 'endpoints': ['master.example.net', 'master2.example.net']}]}) 

TASK [icinga.icinga.icinga2 : feature api ApiListener object name=api, type=ApiListener, file=features-available/api.conf, args={{ args }}] *******************************************************************************************************************************************************************
--- before: /var/tmp/icinga/features-available/api.conf/10_apilistener-api
+++ after: /var/tmp/icinga/features-available/api.conf/10_apilistener-api
@@ -1,5 +1,5 @@
 object ApiListener "api" {
-  accept_config = true
+  ticket_salt = TicketSalt
+  accept_config = false
   accept_commands = true
-  ticket_salt = TicketSalt
 }

changed: [myhost.example.net]

TASK [icinga.icinga.icinga2 : set_fact icinga2_local_objects={{ icinga2_local_objects|default([]) + [result.dest] }}] *****************************************************************************************************************************************************************************************
ok: [myhost.example.net]

[...]

TASK [icinga.icinga.icinga2 : collect all config objects in play vars tmp_objects={{ tmp_objects| default([]) + lookup('list', icinga2_objects) }}] ***********************************************************************************************************************************************************
ok: [myhost.example.net]

TASK [icinga.icinga.icinga2 : icinga2_object args={{ item }}] *************************************************************************************************************************************************************************************************************************************************
--- before: /var/tmp/icinga/features-available/api.conf/10_apilistener-api
+++ after: /var/tmp/icinga/features-available/api.conf/10_apilistener-api
@@ -1,5 +1,5 @@
 object ApiListener "api" {
+  accept_config = true
+  accept_commands = true
   ticket_salt = TicketSalt
-  accept_config = false
-  accept_commands = true
 }

changed: [myhost.example.net] => (item={'name': 'api', 'type': 'ApiListener', 'accept_config': True, 'accept_commands': True})
ok: [myhost.example.net] => (item={'name': 'api', 'type': 'ApiListener', 'accept_config': True, 'accept_commands': True})

TASK [icinga.icinga.icinga2 : set_fact icinga2_local_objects={{ icinga2_local_objects|default([]) + [item.dest] }}] *******************************************************************************************************************************************************************************************
ok: [myhost.example.net] => (item={'path': '/var/tmp/icinga/features-available/api.conf/', 'changed': True, 'diff': [{'before_header': '/var/tmp/icinga/features-available/api.conf/10_apilistener-api', 'before': 'object ApiListener "api" {\n  ticket_salt = TicketSalt\n  accept_config = false\n  accept_commands = true\n}\n', 'after_header': '/var/tmp/icinga/features-available/api.conf/10_apilistener-api', 'after': 'object ApiListener "api" {\n  accept_config = true\n  accept_commands = true\n  ticket_salt = TicketSalt\n}\n'}], 'uid': 0, 'gid': 0, 'owner': 'root', 'group': 'root', 'mode': '0644', 'state': 'file', 'size': 104, 'invocation': {'module_args': {'state': 'directory', 'path': '/var/tmp/icinga/features-available/api.conf/', 'recurse': False, 'force': True, 'follow': False, 'modification_time_format': '%Y%m%d%H%M.%S', 'access_time_format': '%Y%m%d%H%M.%S', 'unsafe_writes': False, '_original_basename': '.kc42816o', '_diff_peek': None, 'src': '/home/ansible/.ansible/tmp/ansible-tmp-1739269790.854195-142-79596844692226/.source', 'modification_time': None, 'access_time': None, 'mode': None, 'owner': None, 'group': None, 'seuser': None, 'serole': None, 'selevel': None, 'setype': None, 'attributes': None, 'dest': '/var/tmp/icinga/features-available/api.conf/10_apilistener-api', 'checksum': '8d271d8021bf9af800991ec10b5f2f44271f396e', 'backup': False, 'content': None, 'validate': None, 'directory_mode': None, 'remote_src': None, 'local_follow': None}}, 'dest': '/var/tmp/icinga/features-available/api.conf/10_apilistener-api', 'src': '/home/ansible/.ansible/tmp/ansible-tmp-1739269790.854195-142-79596844692226/.source', 'md5sum': '7b10fe29b907fbbba4d6c4f65d987dd3', 'checksum': '8d271d8021bf9af800991ec10b5f2f44271f396e', 'failed': False, 'item': {'name': 'api', 'type': 'ApiListener', 'accept_config': True, 'accept_commands': True}, 'ansible_loop_var': 'item'})
ok: [myhost.example.net] => (item={'path': '/var/tmp/icinga/features-available/api.conf/10_apilistener-api', 'changed': False, 'diff': {'before': {'path': '/var/tmp/icinga/features-available/api.conf/10_apilistener-api'}, 'after': {'path': '/var/tmp/icinga/features-available/api.conf/10_apilistener-api'}}, 'uid': 0, 'gid': 0, 'owner': 'root', 'group': 'root', 'mode': '0644', 'state': 'file', 'size': 104, 'invocation': {'module_args': {'state': 'file', 'path': '/var/tmp/icinga/features-available/api.conf/10_apilistener-api', 'recurse': False, 'force': False, 'follow': True, 'modification_time_format': '%Y%m%d%H%M.%S', 'access_time_format': '%Y%m%d%H%M.%S', 'unsafe_writes': False, '_original_basename': '.4lrnm99i', '_diff_peek': None, 'src': None, 'modification_time': None, 'access_time': None, 'mode': None, 'owner': None, 'group': None, 'seuser': None, 'serole': None, 'selevel': None, 'setype': None, 'attributes': None, 'dest': '/var/tmp/icinga/features-available/api.conf/10_apilistener-api'}}, 'checksum': '8d271d8021bf9af800991ec10b5f2f44271f396e', 'dest': '/var/tmp/icinga/features-available/api.conf/10_apilistener-api', 'failed': False, 'item': {'name': 'api', 'type': 'ApiListener', 'accept_config': True, 'accept_commands': True}, 'ansible_loop_var': 'item'})

[...]
```

**Comment by thesefer** [comment]
this is my current host_vars for that specific agent. I oriented myself using the Agent tab in the director (and examining the script there) and a manual setup. 

So do I not need a parent reference nor the accept_commands / accept_config? I am confused to be honest.

`icinga-cluster` = icinga-masters

```
icinga2_features:
  - name: api           # Enable Feature API
    ca_host: "{{ groups['icinga-cluster'][0] }}"
    cert_name: "{{ inventory_hostname }}"
    # Trusted Cert and Ticket will be gathered from this host.
    # Ticket will be "delegated" if the FQDN is not in your Ansible environment
    # use the variable icinga2_delegate_host in addition.
    endpoints:
      - name: NodeName
      - name: "{{ groups['icinga-cluster'][0] }}"
      - name: "{{ groups['icinga-cluster'][1] }}"
    zones:
      - name: NodeName
        parent: main
        endpoints:
          - NodeName
      - name: main
        endpoints:
          - "{{ groups['icinga-cluster'][0] }}"
          - "{{ groups['icinga-cluster'][1] }}"
      - name: director-global
        global: true
  - name: notification
    state: absent
```

Without parent I get: `Remote Icinga instance 'agent.example.net' is not connected to 'master.example.net'`.
Without `accept_config` and `accept_commands` i get: i.e. `Check command 'cmd-check-cpu-usage' does not exist.`

(I am using linuxfabrik's monitoring plugins and command/service/... set)
