### ISSUE TITLE
salt exposed on agents api.conf

### ISSUE THREAD

**Issue by thesefer** [Icinga/ansible-collection-icinga#371]
Hi, in https://github.com/Icinga/ansible-collection-icinga/pull/222/files the ability to delegate ticket creation to satellites got added.

Today I noticed the ticket_salt exposed in `features-enabled/api.conf` on all agents/satellites. According to https://icinga.com/docs/icinga-2/latest/doc/06-distributed-monitoring/#csr-auto-signing-on-the-master the salt shall never be exposed.

I expected it to only be used in [delegate ticket request to master](https://github.com/Icinga/ansible-collection-icinga/blob/main/roles/icinga2/tasks/features/api.yml#L139). Currently using https://github.com/Icinga/ansible-collection-icinga/commit/ae45fa9e7f84ce1a8d74fe772f81b95f66f0a67a.

It's written during `TASK [icinga.icinga.icinga2 : assemble config files src={{ item.path }}]`

vars in clients.yaml
```
icinga2_constants:
  NodeName: "{{ inventory_hostname }}"
  ZoneName: "{{ inventory_hostname }}"

icinga2_confd: false
icinga2_purge_features: yes

icinga2_features:
  - name: notification
    state: absent
  - name: mainlog
    severity: information
  - name: checker
  - name: api
    ca_host: "{{ groups['icinga_satellites'][0] }}"
    ticket_salt: "{{ icinga2_global_ticketsalt }}"
    cert_name: "{{ inventory_hostname }}"
    force_newcert: yes
    accept_config: true
    accept_commands: true
    endpoints:
      - name: NodeName
      - name: "{{ groups['icinga_satellites'][0] }}"
    zones:
      - name: ZoneName
        parent: satellite
        endpoints:
          - NodeName
      - name: satellite
        endpoints:
          - "{{ groups['icinga_satellites'][0] }}"
      - name: global-templates
        global: true
      - name: director-global
        global: true
```
