### ISSUE TITLE
Password of ApiUser is incorrectly quoted

### ISSUE THREAD

**Issue by Jonny007-MKD** [Icinga/ansible-collection-icinga#378]
`Icinga2Parser.parse()` does incorrectly quote complex passwords with special characters like this one:

```
icinga2_objects:
  - name: foo
    type: ApiUser
    password: "h/2&{F1(i>/aX#k~|@"
    permissions:
      - "objects/query/*"
      - "events/*"
      - "status/query"
      - "actions/acknowledge-problem"
    file: "{{ 'conf.d/api-user.conf' }}"
```

This is the resulting file:
```
object ApiUser "foo" {
  password = h/2&{F1("i>/aX#k~|@"
  permissions = [ "objects/query/*", "events/*", "status/query", "actions/acknowledge-problem", ]
}
```

As you can see the quotes are incorrectly put inside the password, i.e. after the parenthesis.
