### ISSUE TITLE
feature influxdb renders host_template wrong

### ISSUE THREAD

**Issue by mkayontour** [Icinga/ansible-collection-icinga#75]
The feature produces the wrong output when defining the yaml. 

```
      - name: influxdb
        host: localhost
        port: 8086
        username: influx
        password: influx
        database: influxdb
        host_template:
          measurement: "$host.check_command$"
          tags:
            hostname: "$host.name$"
```

`host_template = "'measurement'": '$host.check_command$'" = "'tags': {'hostname': '-:"$host.name$"'}"`
