### ISSUE TITLE
Add functionality to place agent in downtime

### ISSUE THREAD

**Issue by william-sy** [Icinga/ansible-collection-icinga#96]
It would be great to add a feature where a host with all its services or just one service gets placed into downtime for X amount minutes. 
This would be great for if the server is not ready yet with all its services while its being setup causing alerts /  pages.
Also great for patching or other events that ansible will do with certain services that are monitored like upgrading said service.

**Comment by mkayontour** [comment]
Hi do you mean to set downtimes via the API for hosts and services?

**Comment by william-sy** [comment]
Hi, 
Yes normally you could do something like this:

```bash
curl -k  -u user:password -H 'Accept: application/json' \
 -X POST 'https://icinga.internal:5665/v1/actions/schedule-downtime' \
 -d '{ "type": "Service", "filter": "host.name==\"server.internal\" && service.name==\"ping4\"", "start_time": 1592856490, "end_time": 1592866490, "all_services": true, "author": "ansible", "comment": "Patching!", "pretty": true }'
```

Which works in ansible if you put all kinds of variables there but is not very elegant! 

It would be great if there were: 

```yml
- name: "Place agent into downtime"
  icinga2_downtime:
     host: {{ inventory_hostname }}
     start: {{ some form of date and time }}
     end: {{ some form of date and time }}
     all_service: True/False 
     service: ping4
     comment: "Patching"
     type: flexible/fixed
     child_hosts: None/triggered/non-triggered 
  when: XX
  with_items: XX
```
